os: linux
dist: bionic
language: python
python:
  - "3.7"
  
# limit tested branches
# branches with PRs will only be tested once via https://docs.travis-ci.com/user/pull-requests,
#  instead of twice: https://docs.travis-ci.com/user/pull-requests#double-builds-on-pull-requests
# and master will be tested after merges as a double-check
branches:
  only:
  - master

# command to install dependencies
install:
  - echo "Installation of the repository"
  -
  - # Install bleeding-edge dcm2niix
  - curl -JLO https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_lnx.zip
  - unzip -o dcm2niix_lnx.zip
  - sudo install dcm2nii* /usr/bin/
  -
  - pip install .
  - pip install coveralls
# command to run tests
script:
  - echo "Download prelude"
  - st_download_data prelude
  - echo "Set up prelude"
  - prelude_path="`pwd`"/prelude
  - chmod 500 ${prelude_path}/prelude
  - PATH=${prelude_path}:${PATH}
  - export PATH
  - FSLOUTPUTTYPE=NIFTI_GZ
  - export FSLOUTPUTTYPE
  - echo "Launch general integrity test"
  - py.test . -v --cov shimmingtoolbox/ --cov-report term-missing
  # Fail if any .sh files have warnings
  - echo "Check Bash scripts"
  - shellcheck examples/*.sh
after_success:
  - coveralls
